# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

trigger:
  branches:
    include:
    - master

pool:
  vmImage: windows-latest

stages:
# - stage: Tests
#   jobs:
#   - job: 
#     displayName: Unit tests
#     steps:
#     - script: echo simulate running your unit tests!
#       displayName: 'Run unit tests'
#   - job: 
#     displayName: UI tests
#     steps:
#     - script:  echo simulate running your ui tests!
#       displayName: 'Run unit tests'

- stage: Build
  dependsOn: [] # This will remove implicit dependency and run in parallel with the stage: Tests above 
  jobs:
  - job:
    displayName: Build the application
    steps:
    - script: |
        call yarn install
        call yarn build
      displayName: 'yarn install and build'
      workingDirectory: '$(Build.SourcesDirectory)/src/'
    
    - task: CopyFiles@2
      displayName: 'Copy scripts'
      inputs:
        contents: 'dist/**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.SourcesDirectory)/src/'
      artifact: drop







    # - task: AzureFileCopy@4
    #   inputs:
    #     sourcePath: '$(Build.SourcesDirectory)/dist/**/*'
    #     azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
    #     destination: azureBlob
    #     storage: 'visiophonewebstoreage'
    #     containerName: '$web'
    #     cleanTargetBeforeCopy: true

    # - task: AzureFileCopy@4
    #   inputs:
    #     sourcePath: '$(Build.SourcesDirectory)/dist/index.html'
    #     azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
    #     destination: azureBlob
    #     storage: 'visiophonewebstoreage'
    #     containerName: '$web'
    #     cleanTargetBeforeCopy: true