# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

trigger:
  branches:
    include:
    - master

pool:
  vmImage: windows-latest

stages:
- stage: Build
  dependsOn: [] # This will remove implicit dependency and run in parallel with the stage: Tests above 
  jobs:
  - job:
    pool:
      vmImage: 'windows-latest'
    displayName: Build the application
    steps:
    - script: |
        call yarn install
        call yarn build
      displayName: 'yarn install and build'
      workingDirectory: '$(Build.SourcesDirectory)/'
    
    - task: CopyFiles@2
      displayName: 'Copy scripts'
      inputs:
        contents: 'dist/**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - publish: '$(Build.SourcesDirectory)/dist/'
      artifact: _FrontEnd_dev

# - stage: dev
#   dependsOn:
#   - Build
#   jobs:
#     - job: run_test
#       pool:
#         vmImage: 'windows-latest'
#       steps:
#       - download: current
#         artifact: drop
#       - task: PowerShell@2
#         inputs:
#           filePath: '$(Pipeline.Workspace)\drop\**'

#       - task: AzureFileCopy@4
#         inputs:
#           sourcePath: '$(Pipeline.Workspace)/drop/dist/**/*'
#           azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
#           destination: azureBlob
#           storage: 'visiophonewebstoreage'
#           containerName: '$web'
#           cleanTargetBeforeCopy: true



            #   - script: echo Running in the Dev environment as deployment job
            #   displayName: 'Dev based stage'
            # - task: AzureFileCopy@4
            #   inputs:
            #   SourcePath: '$(buildOutputFolder)/*'
            #   azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
            #   Destination: 'AzureBlob'
            #   storage: 'visiophonewebstoreage'
            #   ContainerName: '$web'


    # - task: AzureFileCopy@4
    #   inputs:
    #     sourcePath: '$(Build.SourcesDirectory)/dist/**/*'
    #     azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
    #     destination: azureBlob
    #     storage: 'visiophonewebstoreage'
    #     containerName: '$web'
    #     cleanTargetBeforeCopy: true

    # - task: AzureFileCopy@4
    #   inputs:
    #     sourcePath: '$(Build.SourcesDirectory)/dist/index.html'
    #     azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
    #     destination: azureBlob
    #     storage: 'visiophonewebstoreage'
    #     containerName: '$web'
    #     cleanTargetBeforeCopy: true