# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

trigger:
  branches:
    include:
    - master

pool:
  vmImage: windows-latest

stages:
- stage: Tests
  jobs:
  - job: 
    displayName: Unit tests
    steps:
    - script: echo simulate running your unit tests!
      displayName: 'Run unit tests'
  - job: 
    displayName: UI tests
    steps:
    - script:  echo simulate running your ui tests!
      displayName: 'Run unit tests'

- stage: Build
  dependsOn: [] # This will remove implicit dependency and run in parallel with the stage: Tests above 
  jobs:
  - job:
    displayName: Build the application
    steps:
    - script: |
        call yarn install
        call yarn build
      displayName: 'yarn install and build'
      workingDirectory: '$(Build.SourcesDirectory)'
    - publish: '$(buildOutputFolder)/dist/*'
      artifact: WebApp

- stage: dev
  dependsOn:
  - Tests
  - Build
  jobs:
  - deployment:
    displayName: dev deploy
    environment: dev
    strategy:
     runOnce:
       deploy:
         steps:
          - script: echo Running in the Dev environment as deployment job
            displayName: 'Dev based stage'
          - task: AzureFileCopy@4
            inputs:
              SourcePath: '$(buildOutputFolder)/*'
              azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
              Destination: 'AzureBlob'
              storage: 'visiophonewebstoreage'
              ContainerName: '$web'