# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# define the VM image I want to use for my build
pool:
  vmImage: windows-latest

# define variables to use during the build
variables:
  projectFolder: './'
  buildOutputFolder: 'dist'

# define the steps of the build
steps:

## Run the npm install/build
- script: |
    call yarn install
    call yarn build
  displayName: 'yarn install and build'
  workingDirectory: '$(Build.SourcesDirectory)'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(buildOutputFolder)/**/**'
    azureSubscription: 'WorkOnSubscription(e1896010-0921-499e-a947-f5aef5306277)'
    Destination: 'AzureBlob'
    storage: 'visiophonewebstoreage'
    ContainerName: '$web'